apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvol-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/nfs-k8s-pv
    server: 192.169.32.20   #<-- Edit to match master node  (private IP for AWS)
    readOnly: false
