apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: container1
    image: centos
    env:
    - name: MESSAGE
      value: "Hello Centos"
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo '$(MESSAGE)'; sleep 10;done"]
  - name: container2
    image: busybox
    env:
    - name: MESSAGE
      value: "Hello busybox"
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo '$(MESSAGE)'; sleep 10;done"]
  - name: nginx
    image: nginx
    ports: 
      - containerPort: 80